class Constants:
    SCREEN_WIDTH = 1050
    SCREEN_HEIGHT = 650
    VIEWPORT_HEIGHT = 600
    SIDEBAR_SIZE = 250
    VIEWPORT_LENGTH = SCREEN_HEIGHT - SIDEBAR_SIZE
    VIEWPORT_WIDTH = SCREEN_WIDTH - SIDEBAR_SIZE