class Constants:
    SCREEN_WIDTH = 1280
    SCREEN_HEIGHT = 720
    VIEWPORT_HEIGHT = 600
    SIDEBAR_SIZE = 250
    VIEWPORT_SLACK = 0
    VIEWPORT_WIDTH = SCREEN_HEIGHT - SIDEBAR_SIZE - VIEWPORT_SLACK
    VIEWPORT_LENGTH = SCREEN_WIDTH - SIDEBAR_SIZE - VIEWPORT_SLACK